#!/bin/bash
#
# Deb-build plugin for git-pkg
#  by Devaev Maxim <mdevaev@gmail.com> (c) 2011 v0.1
#
#####


. git-sh-setup

PKG_TYPE_deb="1"


#####
PKG_DEB_DEST="git-pkg-deb"
PKG_DEB_BUILDROOT="$PKG_DEB_DEST/buildroot"


#####
deb_check_config() {
    [ -z "$DEBFULLNAME" ] || FULLNAME="$DEBFULLNAME"
    [ -z "$DEBMAIL" ] || EMAIL="$DEBMAIL"
}


#####
deb_project_name() {
    git show HEAD:debian/control | grep "Source:" | awk '{print $2}'
}

deb_last_version() {
    git show HEAD:debian/changelog | head -n 1 | awk '{print $2}' | sed -e 's/^(\(.*\))$/\1/g'
}


#####
deb_update_changelog() {
    local project_name=`deb_project_name`
    local now=`LC_ALL="C" date -R`

    echo -e "$project_name (~~~) unstable; urgency=low\n" > debian/changelog.new
    sed -e 's/^\(.*\)$/  * \1/g' >> debian/changelog.new
    echo -e "\n -- $FULLNAME <$EMAIL>  $now\n" >> debian/changelog.new

    cat debian/changelog >> debian/changelog.new
    mv debian/changelog.new debian/changelog
}

deb_edit_changelog() {
    $EDITOR debian/changelog

    local new_version=`head -n 1 debian/changelog | awk '{print $2}' | sed -e 's/^(\(.*\))$/\1/g'`
    [ "$new_version" != "~~~" ] || die "Please, specify a correct version instead \"~~~\" in changelog"

    git add -f debian/changelog
    git commit -m "Git-pkg autocommit: $PKG_TYPE changelog for $new_version"
}


deb_build() {
    rm -rf "$PKG_DEB_BUILDROOT"
    mkdir -p "$PKG_DEB_BUILDROOT"
    git checkout-index -f -a --prefix="$PKG_DEB_BUILDROOT/" || return "1"

    pushd "$PKG_DEB_BUILDROOT"
    local debuild_opts=`git config pkg.debuild-opts || echo "--no-tgz-check --no-lintian"`
    if [ -n "$PKG_SCHROOT" ]; then
        LC_ALL="C" schroot -p -c "$PKG_SCHROOT" -- /bin/sh -c "debuild $debuild_opts -a$PKG_ARCH && debuild clean"
    else
        LC_ALL="C" debuild $debuild_opts -a$PKG_ARCH && debuild clean
    fi
    local ret="$?"
    popd

    [ "$ret" -ne "0" ] || rm -rf "$PKG_DEB_BUILDROOT"

    return "$ret"
}

