#!/bin/bash
#
# ArchLinux PKGBUILD plugin for git-pkg
#  by Devaev Maxim <mdevaev@gmail.com> (c) 2011 v0.1
#
#####


source git-sh-setup
source git-pkg-shared


#####
PKG_TYPE_arch="1"

PKG_ARCH_ROOT="pkg-root.arch"
PKG_ARCH_BUILDROOT="$PKG_ARCH_ROOT/buildroot"


#####
arch_init_config() {
	[ -e "PKGBUILD" ] || die "PKGBUILD does not exists"
}


#####
arch_project_name() {
	( source <(git show HEAD:PKGBUILD); echo $pkgname )
}

arch_last_version() {
	( source <(git show HEAD:PKGBUILD); echo $pkgver-$pkgrel )
}


#####
arch_update_changelog() {
	echo "TODO: No standard changelog"
	sed -e 's/^\(.*\)$/  * \1/g'
}

arch_edit_changelog() {
	$EDITOR PKGBUILD

	local new_version=`( source PKGBUILD; echo $pkgver-$pkgrel )`
	[ -n "$new_version" ] || die "Please, specify a correct version in PKGBUILD"

	git add PKGBUILD
	git commit -m "Git-pkg autocommit: $PKG_TYPE PKGBUILD for $new_version"
}


arch_build_prepare() {
	rm -rf "$PKG_ARCH_ROOT"
	mkdir -p "$PKG_ARCH_BUILDROOT"
	git checkout-index -f -a --prefix="$PKG_ARCH_BUILDROOT/" || return "1"
}

arch_build() {
	local project_name=`arch_project_name`
	local makepkg_opts=`git config pkg.makepkg-opts || echo "--holdver --clean"`

	pushd "$PKG_ARCH_BUILDROOT"
	dest_exec "makepkg $makepkg_opts"
	local ret="$?"
	[ "$ret" -ne "0" ] || mv "$project_name"*.tar.* ..
	popd

	return "$ret"
}

arch_build_clean() {
	rm -rf "$PKG_ARCH_BUILDROOT"
}

