#!/bin/bash
#
# Deb-build plugin for git-pkg
#  by Devaev Maxim <mdevaev@gmail.com> (c) 2011 v0.1
#
#####


. git-sh-setup

PKG_TYPE_deb="1"


#####
PKG_DEB_DEST="git-pkg-deb"
PKG_DEB_BUILDROOT="$PKG_DEB_DEST/buildroot"


#####
deb_check_config() {
    [ -z "$DEBFULLNAME" ] || FULLNAME="$DEBFULLNAME"
    [ -z "$DEBMAIL" ] || EMAIL="$DEBMAIL"
}


#####
deb_project_name() {
    git show HEAD:debian/control | grep "Source:" | awk '{print $2}'
}

deb_last_version() {
    git show HEAD:debian/changelog | head -n 1 | awk '{print $2}' | sed -e 's/^(\(.*\))$/\1/g'
}


#####
deb_update_changelog() {
    echo -e "`deb_project_name` (\$VERSION\$) unstable; urgency=low\n" > debian/changelog.new
    sed -e 's/^\(.*\)$/  * \1/g' >> debian/changelog.new
    echo -e "\n -- $FULLNAME <$EMAIL>  `LC_ALL=C date -R`\n" >> debian/changelog.new

    cat debian/changelog >> debian/changelog.new
    mv debian/changelog.new debian/changelog
}

deb_edit_changelog() {
    $EDITOR debian/changelog
}


deb_build() {
    mkdir -p "$PKG_DEB_BUILDROOT"
    git checkout-index -f -a --prefix="$PKG_DEB_BUILDROOT/" || return "1"

    pushd "$PKG_DEB_BUILDROOT"
    local debuild_opts=`git config pkg.debuild-opts || echo "--no-tgz-check --no-lintian"`
    if [ -n "$PKG_SCHROOT" ]; then
        schroot -c "$PKG_SCHROOT" -- /bin/sh -c "debuild $debuild_opts -a$PKG_ARCH && debuild clean"
    else
        debuild $debuild_opts -a$PKG_ARCH && debuild clean
    fi
    local ret="$?"
    popd

    [ "$ret" -ne "0" ] || rm -rf "$PKG_DEB_BUILDROOT"

    return "$ret"
}

