#!/bin/bash
#
# Git-pkg shared functions
#  by Devaev Maxim <mdevaev@gmail.com> (c) 2011 v0.1
#
#####


##### Shared functions #####
paint() {
	# For first argument, see man 4 console_codes
	[ -n "$USE_COLORS" ] && echo -en "\e[1;$1m$2\e[0m" || echo -en "$2"
}

dest_exec() {
	local command="/bin/bash -c '$1'"
	[ -z "$PKG_SCHROOT" ] || local command="LC_ALL=C schroot -p -c '$PKG_SCHROOT' -- $command"
	eval $command
}

